[[redirects]]
  from = "/projects"
  to = "/works"
  status = 200

[[redirects]]
  from = "/MarianoRivas.pdf"
  to = "/rivas-resume-2020.pdf"
  status = 200

[[redirects]]
  from = "/30min"
  to = "https://calendly.com/colormono/30min"
  force = true
  
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCjjS8Wtv6oJyEZBHUSxtZDA"
  force = true

[[redirects]]
  from = "/exp/recreo"
  to = "https://recreo.colormono.com
  force = true